name: load

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  load-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Tarmac
      run: make tarmac-performance 
    - name: Configure Test
      run: |
        cat << EOF > loadtest-config.yml
          url: http://localhost/
          SLOs:
            http/error-rate: 0
            http/latency-p99.9: 5
        EOF
    - uses: iter8-tools/iter8-action@v1
      with:
        chart: load-test-http
        valuesFile: loadtest-config.yml 
